### ISSUE TITLE
[tailscale] Stuck in deploying after updating to 1.0.43 

### ISSUE THREAD

**Issue by maxexcloo** [truenas/charts#2701] opened 2024-08-01 06:14 UTC
My containers no longer run after the update - tested a rollback to the previous version 1.0.42 and all was working again.

Logs show this:
```
2024-08-01 16:11:56.378142+10:00boot: 2024/08/01 06:11:56 error checking get permission on secret tailscale-tailscale-secret: Post "https://kubernetes.default.svc/apis/authorization.k8s.io/v1/selfsubjectaccessreviews": dial tcp: lookup kubernetes.default.svc on 100.100.100.100:53: read udp 192.168.0.3:45884->100.100.100.100:53: i/o timeout
2024-08-01 16:12:16.389336+10:00boot: 2024/08/01 06:12:16 error checking update permission on secret tailscale-tailscale-secret: Post "https://kubernetes.default.svc/apis/authorization.k8s.io/v1/selfsubjectaccessreviews": dial tcp: lookup kubernetes.default.svc on 100.100.100.100:53: read udp 192.168.0.3:36622->100.100.100.100:53: i/o timeout
```

Happy to give any more info needed :)

**Comment by YapWC** [comment] 2024-08-02 02:45
I faced the same issue with 1.0.43. But I manage to have it run after clicking on pause and click on start again for the container to restart. Maybe you can try this too?

Otherwise you may share your configuration on Tailscale. As of now I am running Tailscale 1.0.43 without problem.

**Comment by maxexcloo** [comment] 2024-08-06 03:14
I'll give that a go, just don't want to lose my remote access!

**Comment by stavros-k** [comment] 2024-08-26 11:25
> I'll give that a go, just don't want to lose my remote access!

Hello, Did that work?

I couldn't reproduce it locally.

**Comment by maxexcloo** [comment] 2024-08-28 02:53
I completely uninstalled and reinstalled and had the same issue - very odd

**Comment by maxexcloo** [comment] 2024-08-28 04:00
<img width="504" alt="Screenshot 2024-08-28 at 13 58 26" src="https://github.com/user-attachments/assets/7be1d9c4-a167-48bb-bf6f-24d8d3d7274f">
New config with a new name, same issue:

```
2024-08-28 13:59:26.286844+10:00boot: 2024/08/28 03:59:26 error checking get permission on secret tailscale2-tailscale-secret: Post "https://kubernetes.default.svc/apis/authorization.k8s.io/v1/selfsubjectaccessreviews": dial tcp: lookup kubernetes.default.svc on 100.100.100.100:53: read udp 192.168.0.3:34019->100.100.100.100:53: i/o timeout
2024-08-28 13:59:46.300039+10:00boot: 2024/08/28 03:59:46 error checking update permission on secret tailscale2-tailscale-secret: Post "https://kubernetes.default.svc/apis/authorization.k8s.io/v1/selfsubjectaccessreviews": dial tcp: lookup kubernetes.default.svc on 100.100.100.100:53: read udp 192.168.0.3:41605->100.100.100.100:53: i/o timeout
```

It starts up, adds itself to the tailscale admin and then restarts and won't start after that...

**Comment by maxexcloo** [comment] 2024-08-31 01:14
Just saw the news about docker, I guess it’ll work with that ☀️

**Comment by stavros-k** [comment] 2024-09-03 05:41
It should be better there, yes!
I'll close this one as its very similar to https://github.com/truenas/charts/issues/1874.
Thanks!

**Closed by stavros-k** 2024-09-03 05:41 UTC
