### ISSUE TITLE
Community chart suggestion : Prowlarr

### ISSUE THREAD

**Issue by Maxoobidou** [truenas/charts#1160] opened 2023-04-26 16:46 UTC
As described in the wikiarrr article about it [here ](https://wiki.servarr.com/prowlarr):

> Prowlarr is an indexer manager/proxy built on the popular arr .net/reactjs base stack to integrate with your various PVR apps. Prowlarr supports management of both Torrent Trackers and Usenet Indexers. It integrates seamlessly with Lidarr, Mylar3, Radarr, Readarr, and Sonarr offering complete management of your indexers with no per app Indexer setup required (we do it all).

Basically, Prowlarr is a virtualization layer for indexer used in *arr apps like Sonarr or Radarr.
Pros : you only set up indexers once, you can search directly in prowlarr if you want a specific file, you can sync all your apps.

source : [https://github.com/Prowlarr/Prowlarr](https://github.com/Prowlarr/Prowlarr)

**Comment by pavleknezevic** [comment] 2023-07-10 21:51
Duplicate of #1094

**Closed** 2023-07-12 14:27 UTC
Labels: app request
