### ISSUE TITLE
Nextcloud outdated and unsupported postgres version

### ISSUE THREAD

**Issue by tchey290** [truenas/charts#2855] opened 2024-10-07 00:21 UTC
Nextcloud chart is currently using version 13.1 for postgres which very outdated and when using memories results in a database trigger error:

`Database triggers not set up; trigger compatibility mode in use.`

Postgres needs to be updated to at least version 14 or higher to support these database triggers.

**Comment by stavros-k** [comment] 2024-10-07 12:29
Duplicate of https://github.com/truenas/apps/issues/342

**Closed by stavros-k** 2024-10-07 12:29 UTC
