### ISSUE TITLE
Community chart suggestion : Homarr

### ISSUE THREAD

**Issue by Maxoobidou** [truenas/charts#1161] opened 2023-04-26 16:52 UTC
As described in the [official website](https://homarr.dev/):

> A simple, yet powerful dashboard for your server.
> 
> Simplify the management of your server with Homarr - a sleek, modern dashboard that puts all of your apps and services at your fingertips. With Homarr, you can access and control everything in one convenient location. Homarr seamlessly integrates with the apps you've added, providing you with valuable information and giving you complete control. Installation is a breeze, and Homarr supports a wide range of deployment methods.

Basically, Homarr enables the creation of a dashboard for your apps very easily and integrates with some of them to display important information/interact with them directly from the dashboard. It supports mobile.

source : [https://github.com/ajnart/homarr](https://github.com/ajnart/homarr)

**Comment by pavleknezevic** [comment] 2023-07-10 21:51
Duplicate of #1094

**Closed** 2023-07-12 14:28 UTC
Labels: app request
