### ISSUE TITLE
Error Nextcloud with Redis

### ISSUE THREAD

**Issue by IsmaStifler** [truenas/charts#1713] opened 2023-11-07 23:57 UTC
Hi, I'm checking that when I enable redis, my external storage becomes inaccessible, even though it appears green, it doesn't show up in my files.

I understand what a bug with redis?

```
<?php
if (getenv('REDIS_HOST')) {
  $CONFIG = array(
    'memcache.distributed' => '\OC\Memcache\Redis',
    'memcache.locking' => '\OC\Memcache\Redis',
    'redis' => array(
      'host' => getenv('REDIS_HOST'),
      'password' => (string) getenv('REDIS_HOST_PASSWORD'),
    ),
  );

  if (getenv('REDIS_HOST_PORT') !== false) {
    $CONFIG['redis']['port'] = (int) getenv('REDIS_HOST_PORT');
  } elseif (getenv('REDIS_HOST')[0] != '/') {
    $CONFIG['redis']['port'] = 6379;
  }
}

```

Add to config.php

```
'filelocking.enabled' => true,
'memcache.locking' => '\OC\Memcache\Redis',
'redis' => array(
'host' => 'localhost',
'port' => 6379,
'timeout' => 0.0,
'password' => '', // Optional, if not defined no password will be used.
),

```

**Comment by stavros-k** [comment] 2023-11-08 12:36
I'm not sure what the issue is here, our Nextcloud does not have a redis service built-in yet (#1304), 
If its a configuration issue on Nextcloud, you should ask in the Nextcloud's support channel.

**Comment by IsmaStifler** [comment] 2023-11-09 01:13
> I'm not sure what the issue is here, our Nextcloud does not have a redis service built-in yet (#1304), If its a configuration issue on Nextcloud, you should ask in the Nextcloud's support channel.

![image](https://github.com/truenas/charts/assets/19431908/6555943b-e396-494d-a3d0-0598dcf64618)

**Comment by IsmaStifler** [comment] 2023-11-09 01:15
> Seems to me like the port is wrong. you have to use the external port that was used in the Redis app. (At least port 9000)

yes, install the redis app allocate everything but like nothing, when I activate redis I can't access the external storage mounts, they become inaccessible

**Comment by stavros-k** [comment] 2023-11-09 12:16
I still don't think the issue is on our Application.
I'd suggest you reach to Nextcloud's support channels

**Comment by stavros-k** [comment] 2023-11-14 14:23
Closing this, you can track addition of redis dependency in the linked issue above.

**Closed by stavros-k** 2023-11-14 14:23 UTC
