### ISSUE TITLE
Omada controller 5.14 unable to start

### ISSUE THREAD

**Issue by MilosHampl** [truenas/charts#2756] opened 2024-08-23 08:57 UTC
omada-controller:5.14 container is unable to start: 

`ERROR [main] [] c.t.s.o.s.t.SpringBootStartUpTask(): Cannot retry start up springboot. reson:Error creating bean with name 'com.tplink.smb.omada.identityaccess.domain.model.openapi.c.q': Unsatisfied dependency expressed through field 'e'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.tplink.smb.omada.identityaccess.port.common.a.a': Unsatisfied dependency expressed through field 'c'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.tplink.smb.omada.identityaccess.port.common.e.a': Unsatisfied dependency expressed through field 'b'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.tplink.smb.omada.identityaccess.b.p': Unsatisfied dependency expressed through field 'm'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.tplink.smb.omada.identityaccess.domain.model.user.A': Unsatisfied dependency expressed through field 'c'; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'com.tplink.smb.omada.identityaccess.port.mongo.adaptor.persistence.tenant.a': Bean with name 'com.tplink.smb.omada.identityaccess.port.mongo.adaptor.persistence.tenant.a' has been injected into other beans [com.tplink.smb.omada.identityaccess.domain.model.d.q] in its raw version as part of a circular reference, but has eventually been wrapped. This means that said other beans do not use the final version of the bean. This is often the result of over-eager type matching - consider using 'getBeanNamesForType' with the 'allowEagerInit' flag turned off, for example.
 `

**Comment by stavros-k** [comment] 2024-08-23 10:32
Duplicate of #2729.

**Closed by stavros-k** 2024-08-23 10:32 UTC

**Comment by blacksteel1288** [comment] 2024-08-23 12:33
Yes, this is the error I've been seeing for the past two weeks, preventing the app from starting.

**Comment by blacksteel1288** [comment] 2024-08-28 02:22
This update now fails with a different error, and the container does not start:

There are a series of errors in the log similar to this, then it fails and attempts to restart.

`08-27-2024 22:12:45.195 ERROR [comm-pool-2] [] c.t.s.e.d.DefaultDomainEventBus(): Event handle error. subscriber:com.tplink.smb.omada.client.port.mongo.data.statistic.connectfailure.fivemin.b@67528fd0`
