### ISSUE TITLE
[BUG] Nginx Proxy Manager - Startup probe failed: NOT OK

### ISSUE THREAD

**Issue by pabloeisenhut** [truenas/charts#2038] opened 2024-01-14 11:42 UTC
Whenever the Nginx Proxy Manager is restarted, it issues the error: Startup probe failed: NOT OK. After a while it starts anyway, but it takes some time.

**Comment by stavros-k** [comment] 2024-01-15 09:55
Duplicate of #1212

**Closed by stavros-k** 2024-01-15 09:55 UTC
