### ISSUE TITLE
Community Chart Suggestion: Flaresolverr

### ISSUE THREAD

**Issue by bitpushr** [truenas/charts#2591] opened 2024-06-20 07:37 UTC
https://github.com/FlareSolverr/FlareSolverr

**Comment by kpervin** [comment] 2024-07-12 22:22
@stavros-k any updates? Anything that can be done to help?

**Comment by dvgm506** [comment] 2024-07-17 00:31
Since Flaresolverr is just a simple service container, you should be able to just add it as a custom app. Only thing I needed to do was give it a a node port.

**Comment by vendeesign** [comment] 2024-07-17 13:17
@dvgm506 Why not integrate it like any other app in the catalog, so that it's simple for everyone (click-install) with updates coming like any other app. 

There have been plenty of tickets here and on reddit for this request, for several months/weeks since truecharts(.)org support ended 

Thank you.

**Comment by dvgm506** [comment] 2024-07-17 22:10
> @dvgm506 Why not integrate it like any other app in the catalog, so that it's simple for everyone (click-install) with updates coming like any other app.
> 
> There have been plenty of tickets here and on reddit for this request, for several months/weeks since truecharts(.)org support ended
> 
> Thank you.

Not disagreeing with you. I'm guessing iX staff and community chart creators/maintainers are putting more time & effort into docker-compose repo than creating/changing helm charts. They'll need that done to have people start testing with nightlies once they remove k3s. 5 weeks til EE beta, I'm guessing their are working their tails off!

QbittorrentVPN was one of the very first requests in 2023 for community apps and it's never been done.

BTW, adding it as a custom app with latest image tag will give you updates in the Scale app UI.

If you look at the charts from official, community (or looked at TC's before they nuked it), they are pretty much all using images from some other repo. In this case, TC's used the flaresolverr/flaresolverr repo you linked.

**Comment by stavros-k** [comment] 2024-08-26 14:25
duplicate of https://github.com/truenas/apps/issues/165

**Closed by stavros-k** 2024-08-26 14:25 UTC
Labels: app request
