### ISSUE TITLE
Request - Redis and ACPu in nextcloud

### ISSUE THREAD

**Issue by jwojtas10** [truenas/charts#1843] opened 2023-12-07 17:17 UTC
Redis Server and ACPu, can really improve performance of Nextcloud. There is an alert in Nextcloud admin panel that it should be installed.

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html

**Comment by stavros-k** [comment] 2023-12-11 12:47
Duplicate of #1304

**Closed by stavros-k** 2023-12-11 12:47 UTC
