### ISSUE TITLE
Community Chart Suggestion: Flaresolverr

### ISSUE THREAD

**Issue by Apprisco** [truenas/charts#2596] opened 2024-06-20 12:51 UTC
Flaresolverr would be a valuable addition to the TrueNAS Community *arr stack.
As of now it only exists on TrueCharts.

**Comment by stavros-k** [comment] 2024-06-20 12:53
Duplicate of https://github.com/truenas/charts/issues/2591

**Closed by stavros-k** 2024-06-20 12:53 UTC
