### ISSUE TITLE
Add Scrutiny

### ISSUE THREAD

**Issue by Eliot-Mess** [truenas/charts#2852] opened 2024-10-06 01:10 UTC
> Scrutiny is a WebUI for smartd S.M.A.R.T monitoring

For **Electric Eel** I guess.

https://github.com/AnalogJ/scrutiny

**Comment by stavros-k** [comment] 2024-10-06 10:21
Duplicate of https://github.com/truenas/apps/issues/273

**Closed by stavros-k** 2024-10-06 10:21 UTC
