### ISSUE TITLE
Nginx-proxy-manager app install bug on vanilla TrueNAS Scale - Startup Probe Fails with NOT OK

### ISSUE THREAD

**Issue by caitken000** [truenas/charts#1856] opened 2023-12-10 04:06 UTC
Version of TrueNAS Scale: TrueNAS-SCALE-23.10.0.1
Version of nginx proxy manager

Repeated attempts to install this app (even when its the only app being installed) using defaul installation settings on a clean TrueNAS Scale instance results in a container startup probe error of NOT OK.

Installation settings:
![image](https://github.com/truenas/charts/assets/31361460/ab5d600a-3520-4f18-b62a-127f0a543a19)
![image](https://github.com/truenas/charts/assets/31361460/60dc9ebc-5556-4002-b231-e22146335400)

Kubernetes event log is:
2023-12-10 13:26:59
Startup probe failed: NOT OK
2023-12-10 13:26:26
Created container nginx-proxy-manager
2023-12-10 13:26:26
Started container nginx-proxy-manager
2023-12-10 13:26:25
Add eth0 [172.16.2.172/16] from ix-net
2023-12-10 13:26:25
Container image "jc21/nginx-proxy-manager:2.10.4" already present on machine
2023-12-10 13:26:24
Scaled up replica set nginx-proxy-manager-6fd55896c to 1
2023-12-10 13:26:24
Created pod: nginx-proxy-manager-6fd55896c-h8j96
2023-12-10 13:26:24
Successfully assigned ix-nginx-proxy-manager/nginx-proxy-manager-6fd55896c-h8j96 to ix-truenas

Leaving the app to install for an extended period (i.e., 2 days) does not see the app install
Stopping and restarting the app install results in the same error

**Comment by stavros-k** [comment] 2023-12-11 13:29
Most likely duplicate of #1212

Please let me know if its something different.

**Closed by stavros-k** 2023-12-11 13:29 UTC
