### ISSUE TITLE
Community Chart Suggestion: flaresolverr

### ISSUE THREAD

**Issue by vendeesign** [truenas/charts#2619] opened 2024-06-26 15:19 UTC
Hello, Can you add flaresolverr
https://github.com/FlareSolverr/FlareSolverr

**Comment by stavros-k** [comment] 2024-06-26 19:55
Duplicate of #2591

**Closed by stavros-k** 2024-06-26 19:55 UTC

**Comment by vendeesign** [comment] 2024-06-26 20:40
Ok duplicate, but when will it be available? With the MAJ of truecharts, we can no longer install the latest version. Thanks a lot

**Comment by stavros-k** [comment] 2024-06-26 20:49
You can subscribe to the linked issue if you’d like to get notified for any progress when it’s made. Thanks
